runtime:
  mode: client
  log_level: info

client:
  transport_type: ws
  server_addr: 192.168.6.111:12345
  ca_cert_path: certs/ca-cert.pem
  token: admin

server:
  transport_type: ws
  bind_addr: 0.0.0.0:12345
  tun_name: tun1
  tun_addr: 10.0.0.1
  tun_netmask: 255.255.255.0
  tun_destination: 10.0.0.0
  tun_dns_servers: 114.114.114.114,8.8.8.8
  tun_mtu: 1400
  cert_path: certs/server-cert.pem
  key_path: certs/server-key.pem
  token: admin

rules:
  - DST_ADDR,10.0.0.0/8,proxy
  - MATCH,direct

rule_sets:
  geoip_path: rules/geoip/GeoLite2-Country.mmdb

transparent_proxy:
  interface: "以太网"
  smoltcp_addr: 10.0.0.2
  smoltcp_netmask: 255.255.255.0
  smoltcp_gateway: 10.0.0.1
  upstream_server: null
